services:
  postgres:
    image: postgres:15
    container_name: biblio-postgres
    environment:
      POSTGRES_DB: bibliodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bibliosmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
